trigger:
- master

pool: Self-hosted

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: '.\App\gradlew'
    workingDirectory: '.\App\'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false